/*
 * Copyright (c) 2019 Toast Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.toasttab.protokt.codegen.impl

import com.squareup.kotlinpoet.FileSpec
import com.toasttab.protokt.codegen.annotators.Annotator
import com.toasttab.protokt.codegen.annotators.addConstructorFunction
import com.toasttab.protokt.codegen.descriptor.FileDescriptorResolver
import com.toasttab.protokt.codegen.protoc.Message
import com.toasttab.protokt.codegen.protoc.Protocol
import com.toasttab.protokt.codegen.protoc.fileName

object FileBuilder {
    fun buildFile(
        protocol: Protocol
    ): FileSpec? {
        val descs = Annotator.apply(protocol)

        val builder =
            FileSpec.builder(
                protocol.desc.kotlinPackage.toString(),
                fileName(protocol)
            ).apply {
                // https://github.com/square/kotlinpoet/pull/533
                addFileComment(
                    """
                        Generated by protokt version ${protocol.desc.context.version}. Do not modify.
                        Source: ${protocol.desc.name}
                    """.trimIndent()
                )
                indent("    ")
            }

        var anyCodeAdded = false

        descs.forEach {
            anyCodeAdded = true
            builder.addType(it.type.typeSpec)
        }

        descs
            .map { it.type.rawType }
            .filterIsInstance<Message>()
            .forEach {
                anyCodeAdded = true
                addConstructorFunction(it, builder::addFunction)
            }

        if (!protocol.desc.context.lite) {
            val fileDescriptorInfo = FileDescriptorResolver.resolveFileDescriptor(protocol)

            if (fileDescriptorInfo != null) {
                anyCodeAdded = true
                builder.addType(fileDescriptorInfo.fdp)
                fileDescriptorInfo.properties.forEach(builder::addProperty)
            }
        }

        return if (anyCodeAdded) builder.build() else null
    }
}
