@file:Suppress("DEPRECATION")

// Generated by protokt version 0.12.1. Do not modify.
// Source: google/protobuf/any.proto
package com.toasttab.protokt

import com.toasttab.protokt.rt.KtGeneratedFileDescriptor

@Deprecated("use v1")
@KtGeneratedFileDescriptor
object AnyProto {
    val descriptor: FileDescriptor by lazy {
        val descriptorData = arrayOf(
            "\ngoogle/protobuf/any.protogoogle.prot" +
                    "obuf\"&\nAny\n\btype_url (\t\r\nvalue" +
                    " (Bv\ncom.google.protobufB\bAnyProtoPZ" +
                    ",google.golang.org/protobuf/types/known/" +
                    "anypbﾢGPBﾪGoogle.Protobuf.WellKnownT" +
                    "ypesbproto3"
        )

        FileDescriptor.buildFrom(
            descriptorData,
            listOf(

            )
        )
    }
}

@Deprecated("use v1")
val Any.Deserializer.descriptor: Descriptor
    get() = AnyProto.descriptor.messageTypes[0]
