@file:Suppress("DEPRECATION")

// Generated by protokt version 0.12.1. Do not modify.
// Source: google/protobuf/api.proto
package com.toasttab.protokt

import com.toasttab.protokt.rt.KtGeneratedFileDescriptor

@KtGeneratedFileDescriptor
@Deprecated("use v1")
object ApiProto {
    val descriptor: FileDescriptor by lazy {
        val descriptorData = arrayOf(
            "\ngoogle/protobuf/api.protogoogle.prot" +
                    "obuf\$google/protobuf/source_context.pro" +
                    "togoogle/protobuf/type.proto\"ﾁ\nApi" +
                    "\nname (\t(\nmethods (2.google.p" +
                    "rotobuf.Method(\noptions (2.google" +
                    ".protobuf.Option\nversion (\t6\nsou" +
                    "rce_context (2.google.protobuf.Sour" +
                    "ceContext&\nmixins (2.google.proto" +
                    "buf.Mixin\'\nsyntax (2.google.proto" +
                    "buf.Syntax\"ￕ\nMethod\nname (\t\nr" +
                    "equest_type_url (\t\nrequest_streami" +
                    "ng (\b\nresponse_type_url (\t\nr" +
                    "esponse_streaming (\b(\noptions (" +
                    "2.google.protobuf.Option\'\nsyntax (" +
                    "2.google.protobuf.Syntax\"#\nMixin\nn" +
                    "ame (\t\nroot (\tBv\ncom.google.pr" +
                    "otobufB\bApiProtoPZ,google.golang.org/pr" +
                    "otobuf/types/known/apipbﾢGPBﾪGoogle." +
                    "Protobuf.WellKnownTypesbproto3"
        )

        FileDescriptor.buildFrom(
            descriptorData,
            listOf(
                SourceContextProto.descriptor,
                TypeProto.descriptor
            )
        )
    }
}

@Deprecated("use v1")
val Api.Deserializer.descriptor: Descriptor
    get() = ApiProto.descriptor.messageTypes[0]

@Deprecated("use v1")
val Method.Deserializer.descriptor: Descriptor
    get() = ApiProto.descriptor.messageTypes[1]

@Deprecated("use v1")
val Mixin.Deserializer.descriptor: Descriptor
    get() = ApiProto.descriptor.messageTypes[2]
