@file:Suppress("DEPRECATION")

// Generated by protokt version 0.12.1. Do not modify.
// Source: google/protobuf/empty.proto
package com.toasttab.protokt

import com.toasttab.protokt.rt.KtGeneratedFileDescriptor

@Deprecated("use v1")
@KtGeneratedFileDescriptor
object EmptyProto {
    val descriptor: FileDescriptor by lazy {
        val descriptorData = arrayOf(
            "\ngoogle/protobuf/empty.protogoogle.pr" +
                    "otobuf\"\nEmptyB}\ncom.google.protobufB\n" +
                    "EmptyProtoPZ.google.golang.org/protobuf" +
                    "/types/known/emptypb￸ﾢGPBﾪGoogle.P" +
                    "rotobuf.WellKnownTypesbproto3"
        )

        FileDescriptor.buildFrom(
            descriptorData,
            listOf(

            )
        )
    }
}

@Deprecated("use v1")
val Empty.Deserializer.descriptor: Descriptor
    get() = EmptyProto.descriptor.messageTypes[0]
