@file:Suppress("DEPRECATION")

// Generated by protokt version 0.12.1. Do not modify.
// Source: google/protobuf/field_mask.proto
package com.toasttab.protokt

import com.toasttab.protokt.rt.KtGeneratedFileDescriptor

@KtGeneratedFileDescriptor
@Deprecated("use v1")
object FieldMaskProto {
    val descriptor: FileDescriptor by lazy {
        val descriptorData = arrayOf(
            "\n google/protobuf/field_mask.protogoog" +
                    "le.protobuf\"\n\tFieldMask\r\npaths (\tB" +
                    "ﾅ\ncom.google.protobufBFieldMaskProtoP" +
                    "Z2google.golang.org/protobuf/types/know" +
                    "n/fieldmaskpb￸ﾢGPBﾪGoogle.Protobuf" +
                    ".WellKnownTypesbproto3"
        )

        FileDescriptor.buildFrom(
            descriptorData,
            listOf(

            )
        )
    }
}

@Deprecated("use v1")
val FieldMask.Deserializer.descriptor: Descriptor
    get() = FieldMaskProto.descriptor.messageTypes[0]
