@file:Suppress("DEPRECATION")

// Generated by protokt version 0.12.1. Do not modify.
// Source: google/protobuf/source_context.proto
package com.toasttab.protokt

import com.toasttab.protokt.rt.KtGeneratedFileDescriptor

@KtGeneratedFileDescriptor
@Deprecated("use v1")
object SourceContextProto {
    val descriptor: FileDescriptor by lazy {
        val descriptorData = arrayOf(
            "\n\$google/protobuf/source_context.proto" +
                    "google.protobuf\"\"\n\rSourceContext\n\tfile" +
                    "_name (\tBﾊ\ncom.google.protobufBSou" +
                    "rceContextProtoPZ6google.golang.org/pro" +
                    "tobuf/types/known/sourcecontextpbﾢGPBﾪ" +
                    "Google.Protobuf.WellKnownTypesbproto3"
        )

        FileDescriptor.buildFrom(
            descriptorData,
            listOf(

            )
        )
    }
}

@Deprecated("use v1")
val SourceContext.Deserializer.descriptor: Descriptor
    get() = SourceContextProto.descriptor.messageTypes[0]
