@file:Suppress("DEPRECATION")

// Generated by protokt version 0.12.1. Do not modify.
// Source: google/protobuf/timestamp.proto
package com.toasttab.protokt

import com.toasttab.protokt.rt.KtGeneratedFileDescriptor

@KtGeneratedFileDescriptor
@Deprecated("use v1")
object TimestampProto {
    val descriptor: FileDescriptor by lazy {
        val descriptorData = arrayOf(
            "\ngoogle/protobuf/timestamp.protogoogl" +
                    "e.protobuf\"+\n\tTimestamp\nseconds (" +
                    "\r\nnanos (Bﾅ\ncom.google.protobufB" +
                    "TimestampProtoPZ2google.golang.org/pro" +
                    "tobuf/types/known/timestamppb￸ﾢGPBﾪ" +
                    "Google.Protobuf.WellKnownTypesbproto3"
        )

        FileDescriptor.buildFrom(
            descriptorData,
            listOf(

            )
        )
    }
}

@Deprecated("use v1")
val Timestamp.Deserializer.descriptor: Descriptor
    get() = TimestampProto.descriptor.messageTypes[0]
