@file:Suppress("DEPRECATION")

// Generated by protokt version 0.12.1. Do not modify.
// Source: google/protobuf/wrappers.proto
package com.toasttab.protokt

import com.toasttab.protokt.rt.KtGeneratedFileDescriptor

@KtGeneratedFileDescriptor
@Deprecated("use v1")
object WrappersProto {
    val descriptor: FileDescriptor by lazy {
        val descriptorData = arrayOf(
            "\ngoogle/protobuf/wrappers.protogoogle" +
                    ".protobuf\"\nDoubleValue\r\nvalue (\"" +
                    "\n\nFloatValue\r\nvalue (\"\n\nInt64Val" +
                    "ue\r\nvalue (\"\nUInt64Value\r\nvalu" +
                    "e (\"\n\nInt32Value\r\nvalue (\"\n" +
                    "UInt32Value\r\nvalue (\r\"\n\tBoolValue" +
                    "\r\nvalue (\b\"\nStringValue\r\nvalue" +
                    " (\t\"\n\nBytesValue\r\nvalue (Bﾃ\nco" +
                    "m.google.protobufB\rWrappersProtoPZ1goog" +
                    "le.golang.org/protobuf/types/known/wrapp" +
                    "erspb￸ﾢGPBﾪGoogle.Protobuf.WellKno" +
                    "wnTypesbproto3"
        )

        FileDescriptor.buildFrom(
            descriptorData,
            listOf(

            )
        )
    }
}

@Deprecated("use v1")
val DoubleValue.Deserializer.descriptor: Descriptor
    get() = WrappersProto.descriptor.messageTypes[0]

@Deprecated("use v1")
val FloatValue.Deserializer.descriptor: Descriptor
    get() = WrappersProto.descriptor.messageTypes[1]

@Deprecated("use v1")
val Int64Value.Deserializer.descriptor: Descriptor
    get() = WrappersProto.descriptor.messageTypes[2]

@Deprecated("use v1")
val UInt64Value.Deserializer.descriptor: Descriptor
    get() = WrappersProto.descriptor.messageTypes[3]

@Deprecated("use v1")
val Int32Value.Deserializer.descriptor: Descriptor
    get() = WrappersProto.descriptor.messageTypes[4]

@Deprecated("use v1")
val UInt32Value.Deserializer.descriptor: Descriptor
    get() = WrappersProto.descriptor.messageTypes[5]

@Deprecated("use v1")
val BoolValue.Deserializer.descriptor: Descriptor
    get() = WrappersProto.descriptor.messageTypes[6]

@Deprecated("use v1")
val StringValue.Deserializer.descriptor: Descriptor
    get() = WrappersProto.descriptor.messageTypes[7]

@Deprecated("use v1")
val BytesValue.Deserializer.descriptor: Descriptor
    get() = WrappersProto.descriptor.messageTypes[8]
